In [46]:
nombres_list = list(open('nombres.txt', 'r'))
print(nombres_list)
lista_final = [n.replace("\n", '').replace("'", '').replace(",", '').strip() for n in nombres_list] # List comprenhension
print(lista_final)


#print('Agustin,'.replace(',',)
#zip, 
#map
#dict comprehension

a = ['A','B', 'C']
b = [1,2,3]
c = [10,20,30]
d = {}
d['clave'] = 0
print(d)
d['clave'] = 0+2
print(d['clave']+2)
print(d)

["'Agustin',\n", " 'Lucas',\n", " 'Pedro'\n"]
['Agustin', 'Lucas', 'Pedro']
{'clave': 0}
4
{'clave': 2}

In [8]:

nombres = [
'Agustin',
 'Alan',
 'Andrés',
 'Ariadna',
 'Bautista',
 'CAROLINA',
 'CESAR',
 'David',
 'Diego',
 'Dolores',
 'DYLAN',
 'ELIANA',
 'Emanuel',
 'Fabián',
 'Facundo',
 'Facundo',
 'FEDERICO',
 'FEDERICO',
 'GONZALO',
 'Gregorio',
 'Ignacio',
 'Jonathan',
 'Jonathan',
 'Jorge',
 'JOSE',
 'JUAN',
 'Juan',
 'Juan',
 'Julian',
 'Julieta',
 'LAUTARO',
 'Leonel',
 'LUIS',
 'Luis',
 'Marcos',
 'María',
 'MATEO',
 'Matias',
 'Nicolás',
 'NICOLÁS',
 'Noelia',
 'Pablo',
 'Priscila',
 'TOMAS',
 'Tomás',
 'Ulises',
 'Yanina'
]

eval1 = [
 81,
 60,
 72,
 24,
 15,
 91,
 12,
 70,
 29,
 42,
 16,
 3,
 35,
 67,
 10,
 57,
 11,
 69,
 12,
 77,
 13,
 86,
 48,
 65,
 51,
 41,
 87,
 43,
 10,
 87,
 91,
 15,
 44,
 85,
 73,
 37,
 42,
 95,
 18,
 7,
 74,
 60,
 9,
 65,
 93,
 63,
 74
]

eval2 = [
  30,
 95,
 28,
 84,
 84,
 43,
 66,
 51,
 4,
 11,
 58,
 10,
 13,
 34,
 96,
 71,
 86,
 37,
 64,
 13,
 8,
 87,
 14,
 14,
 49,
 27,
 55,
 69,
 77,
 59,
 57,
 40,
 96,
 24,
 30,
 73,
 95,
 19,
 47,
 15,
 31,
 39,
 15,
 74,
 33,
 57,
 10
]

Creo lista que guarda(agregando con .append), para cada nombre, la suma de sus correspondientes evaluaciones 1 y 2, puesto que la linea i de nombres corresponde a la linea i de eval1 y eval2. La lista es de tuplas, en la que la posicion 0 es el nombre y la 1 la suma de las evaluaciones 1 y 2.

In [9]:
lista_estudiantes = []
for i in range(len(nombres)):
    lista_estudiantes.append((nombres[i],eval1[i]+eval2[i])

Suma en una variable el total de las notas, a partir de recorrer la lista de estudiantes e ir tomando la posicion 1 de la segunda posicion de la tupla. Luego calcula el promedio dividiendo por el largo de la lista (cantidad de estudiantes).

In [10]:
total_notas = 0
for i in range(len(lista_estudiantes)):
    total_notas += lista_estudiantes[i][1]
promedio = int(total_notas/len(lista_estudiantes))

Imprime las posiciones de la lista si, por cada estudiante, la posicion 1 de la tupla (segunda posicion porque empieza por 0) es menor al promedio.

In [11]:
for i in range(len(lista_estudiantes)):
    if lista_estudiantes[i][1] < promedio:
        print(lista_estudiantes[i])

['CESAR', 78]
['Diego', 33]
['Dolores', 53]
['DYLAN', 74]
['ELIANA', 13]
['Emanuel', 48]
['GONZALO', 76]
['Gregorio', 90]
['Ignacio', 21]
['Jonathan', 62]
['Jorge', 79]
['JUAN', 68]
['Julian', 87]
['Leonel', 55]
['Nicolás', 65]
['NICOLÁS', 22]
['Priscila', 24]
['Yanina', 84]